server.port=9000

# Veritaban? URL'si (yeni olu?turdu?un db ismi s19d2)
spring.datasource.url=jdbc:postgresql://localhost:5432/s19d2
spring.datasource.username=postgres
spring.datasource.password=hello

# Hibernate ve ?ema Ayarlar?
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Buras? önemli: Query tool ile açt???n ?ema ismini buraya yaz?yoruz
spring.jpa.properties.hibernate.default_schema=bank

# ?lk kurulumda tablolar?n olu?mas? için
spring.sql.init.mode=always